### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by weseldridge**
This deals with the issue #67.

Are there any other things we need to add to the contributing guide?

### CODE REVIEW

**Comment by cinjon** [comment]
this looks great. only thing that's missing is a couple lines about `pom_tf_battle` as well. mind adding that in and then ill accept?

**Comment by weseldridge** [comment]
Done!

**Comment by cinjon** [comment]
Good add - I meant the pom_tf_battle command though. It's like pom_battle but an additional cli that lets you run tensorforce easily. Given that we have it, I think we should include it here.

**Comment by cinjon** [comment]
Also, one last thing is can we squash the commits together please?

**Comment by weseldridge** [comment]
There is a bit about the tensorforce agent at the bottom of the CLI piece. I am going to push up a change with `pom_tf_battle` instead of direct command.

**Comment by weseldridge** [comment]
If that bit is enough I will squash the commits and push that update.

**Comment by cinjon** [comment]
A+. Thanks!

**Pull request merged**
