### PR TITLE
Fixes 115: Added blocking keyboard player (squashed commits)

### PR DESCRIPTION
**Pull request by pathway**
Same as https://github.com/MultiAgentLearning/playground/pull/206/ but:
- ran yapf on pommerman/agents/player_agent_blocking.py
- squashed to 1 commit

### CODE REVIEW

**Comment by pathway** [comment]
Originally https://github.com/MultiAgentLearning/playground/pull/206

**Comment by cinjon** [comment]
... was the results of yapf saved? i could be wrong but it doesn't appear to be in the expected style. `yapf -i -style google` is what i was thinking.

**Comment by pathway** [comment]
@cinjon I ran yapf only on pommerman/agents/player_agent_blocking.py , my changes are very minor on other files and I wished to avoid extra changes to them.

You can see the format of that file pommerman/agents/player_agent_blocking.py here, it has nice spacing etc from yapf command you requested : https://github.com/MultiAgentLearning/playground/pull/208/files#diff-e11138a06b16ce2c2f6581d2c76f8430

**Comment by cinjon** [comment]
Aye, ok, I am just a little surprised that the `return`s on the same line didn't get brought down to the next line. I suppose that's out of scope.

**Pull request merged**
