### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by PixelyIon**
This improves the documentation significantly.
(PS: We might want to consider a seperate repository for documentations as downloading this with the project is wasting bandwidth)

### CODE REVIEW

**Comment by cinjon** [comment]
1. What's the theme for these changes? What were you going for here?
2. This PR also includes edits to the ion setup. Please separate this from the PR (and create a second one for that code as necessary).

**Comment by PixelyIon** [comment]
1. https://github.com/MultiAgentLearning/playground/issues/171#issuecomment-435407535 mostly sums it up
2. It's because I had to squash it with the previous commit. If you'd cross reference the changes with #172 you'd see it's doing the **exact** same changes. I have no idea as to why it's even showing them in Files Changed.

**Comment by cinjon** [comment]
2. If they're the same, can you extricate those changes please?

**Comment by PixelyIon** [comment]
No idea how I can do this ?

**Comment by cinjon** [comment]
I would have to see the git branch closer. Did you rebase in master? 
Another possibility is that you just start a new branch from master and then copy in the relevant changes.

**Comment by PixelyIon** [comment]
Did some black magic and now it's fixed :)

**Comment by cinjon** [comment]
cool, lgtm.

**Pull request merged**
