### PR TITLE
added a call of episode_end for each agent at the end of an episode

### PR DESCRIPTION
**Pull request by kothiga**
added a call back to the inherited method episode_end from the BaseAgent to envs.v0, at the end of a step if the episode is complete.

### CODE REVIEW

**Comment by cinjon** [comment]
I see what's going on. Currently, we call it [here](https://github.com/MultiAgentLearning/playground/blob/b16c395c347aa4f0ad0284e9e0e351c4bae413d2/pommerman/forward_model.py) in the forward_model and [here](https://github.com/MultiAgentLearning/playground/blob/083346f9dbe996425e480aa4b6bbe2929e3819f9/pommerman/cli/run_battle.py) in run_battle. I think what you're suggesting is that doing it in run_battle is at the wrong level and it should be done lower in the environment itself.

I can get on board with that. Do you want to also remove this from run_battle so that it isn't called twice in succession?

**Comment by kothiga** [comment]
I have removed the episode end call from run_battle. It is still present in forward_model and envs.v0. I could not find an instance where ForwardModel's method run is called.

**Comment by kothiga** [comment]
Yeah, that is no problem. I have merged the master into my fork.

**Comment by cinjon** [comment]
I'm still seeing that there are conflicts. Mind addressing? Also, can you please squash these commits together? (`git rebase -i`)

**Comment by cinjon** [comment]
@kothiga can you finish this off? It would be easier given that you have everything locally and are pretty close.

**Pull request closed without merging**
