### PR TITLE
replace scipy imresize by PIL

### PR DESCRIPTION
**Pull request by F-Schlatt**
imresize was deprecated in scipy 1.0 and removed in scipy 1.3. Failed to run therefore by default on Google Colab

### CODE REVIEW

**Comment by weseldridge** [comment]
Dang, you scipy... Looks good to me. I will run a test of this around lunch. Then we will get it into master. 

Thanks for submitting this!!

giphy

**Comment by cinjon** [comment]
hey, can you fix conflicts please? probably because of the recent rebase on the other PR.

**Comment by cinjon** [comment]
i think this might be pressing because Travis is mad at us about this - https://travis-ci.org/MultiAgentLearning/playground/builds/536773795 . cc @F-Schlatt

**Comment by F-Schlatt** [comment]
Should be resolved

**Comment by F-Schlatt** [comment]
Never mind. You shouldn't resolve conflicts directly on Github :D One second

**Comment by weseldridge** [comment]
If you are pulling it down to fix the conflict and you also squash down the commits?

**Pull request closed without merging**
